"""paper trading sessions

Revision ID: 85ccbcfc5dac
Revises: e23152bde812
Create Date: 2026-07-30 12:00:59.021209

"""

from collections.abc import Sequence

# Custom column types are referenced by qualified name in autogenerated schemas.
import nemonis_db.types
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85ccbcfc5dac"
down_revision: str | Sequence[str] | None = "e23152bde812"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_sessions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("approval_mode", sa.String(length=30), nullable=False),
        sa.Column("risk_profile", sa.String(length=30), nullable=False),
        sa.Column("prop_profile_id", sa.String(length=60), nullable=False),
        sa.Column("instruments", sa.Text(), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("strategy_keys", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("account_currency", sa.String(length=10), nullable=False),
        sa.Column("starting_balance", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("balance", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("equity", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("high_water_mark", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("balance_at_day_start", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("highest_equity_today", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("realised_pnl", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("total_commission", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("trading_day", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.Column("ticks", sa.Integer(), nullable=False),
        sa.Column("signals_generated", sa.Integer(), nullable=False),
        sa.Column("proposals_made", sa.Integer(), nullable=False),
        sa.Column("orders_submitted", sa.Integer(), nullable=False),
        sa.Column("rejections", sa.Integer(), nullable=False),
        sa.Column("closed_trade_count", sa.Integer(), nullable=False),
        sa.Column("started_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("last_tick_at", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.Column("stopped_at", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.Column("updated_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("halt_reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "mode IN ('research', 'backtest', 'paper')", name="ck_paper_session_mode"
        ),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'STOPPED', 'HALTED')", name="ck_paper_session_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("paper_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_paper_sessions_status"), ["status"], unique=False)

    op.create_table(
        "paper_equity_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("equity", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("balance", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("drawdown_pct", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "at", name="uq_paper_equity_at"),
    )
    with op.batch_alter_table("paper_equity_points", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_paper_equity_points_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "paper_positions",
        sa.Column("position_id", sa.String(length=60), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("lots", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("entry_price", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("opened_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("strategy_id", sa.String(length=80), nullable=False),
        sa.Column("stop_loss", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("take_profit", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("commission_paid", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("best_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("worst_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="ck_paper_position_direction"),
        sa.CheckConstraint("lots > '0'", name="ck_paper_position_lots_positive"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("position_id"),
    )
    with op.batch_alter_table("paper_positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_paper_positions_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "paper_trades",
        sa.Column("trade_id", sa.String(length=60), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("strategy_id", sa.String(length=80), nullable=False),
        sa.Column("lots", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("entry_price", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("exit_price", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("opened_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("closed_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("pnl", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("commission", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("exit_reason", sa.String(length=30), nullable=False),
        sa.Column("mfe_pips", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("mae_pips", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("ambiguous_exit", sa.Boolean(), nullable=False),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="ck_paper_trade_direction"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    with op.batch_alter_table("paper_trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_paper_trades_closed_at"), ["closed_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_paper_trades_instrument"), ["instrument"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_paper_trades_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "paper_working_orders",
        sa.Column("order_id", sa.String(length=60), nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("proposal_hash", sa.String(length=80), nullable=False),
        sa.Column("decision_id", sa.String(length=60), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("lifecycle", sa.String(length=20), nullable=False),
        sa.Column("size_lots", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("strategy_id", sa.String(length=80), nullable=False),
        sa.Column("limit_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("stop_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("stop_loss", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("take_profit", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("submitted_at", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="ck_paper_order_direction"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    with op.batch_alter_table("paper_working_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_paper_working_orders_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paper_working_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_working_orders_session_id"))

    op.drop_table("paper_working_orders")
    with op.batch_alter_table("paper_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_trades_session_id"))
        batch_op.drop_index(batch_op.f("ix_paper_trades_instrument"))
        batch_op.drop_index(batch_op.f("ix_paper_trades_closed_at"))

    op.drop_table("paper_trades")
    with op.batch_alter_table("paper_positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_positions_session_id"))

    op.drop_table("paper_positions")
    with op.batch_alter_table("paper_equity_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_equity_points_session_id"))

    op.drop_table("paper_equity_points")
    with op.batch_alter_table("paper_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_sessions_status"))

    op.drop_table("paper_sessions")
    # ### end Alembic commands ###
