"""backtest research records

Revision ID: 8c0f8ac1ea36
Revises: f5af53433bee
Create Date: 2026-07-29 13:44:15.127475

"""

from collections.abc import Sequence

# Custom column types are referenced by qualified name in autogenerated schemas.
import nemonis_db.types
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c0f8ac1ea36"
down_revision: str | Sequence[str] | None = "f5af53433bee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("manifest_hash", sa.String(length=80), nullable=False),
        sa.Column("result_hash", sa.String(length=80), nullable=False),
        sa.Column("manifest_json", sa.Text(), nullable=False),
        sa.Column("manifest_version", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("strategy_key", sa.String(length=80), nullable=False),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("strategy_lifecycle", sa.String(length=30), nullable=False),
        sa.Column("git_commit", sa.String(length=64), nullable=False),
        sa.Column("git_branch", sa.String(length=120), nullable=False),
        sa.Column("git_dirty", sa.Boolean(), nullable=False),
        sa.Column("is_reproducible", sa.Boolean(), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("feature_pipeline_version", sa.String(length=20), nullable=False),
        sa.Column("risk_profile_version", sa.String(length=40), nullable=False),
        sa.Column("market_data_provider", sa.String(length=40), nullable=False),
        sa.Column("dataset_version", sa.String(length=40), nullable=False),
        sa.Column("instruments", sa.Text(), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("data_start", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.Column("data_end", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.Column("bar_count", sa.Integer(), nullable=False),
        sa.Column("provenance", sa.String(length=20), nullable=False),
        sa.Column("spread_assumed", sa.Boolean(), nullable=False),
        sa.Column("spread_model", sa.String(length=40), nullable=False),
        sa.Column("slippage_model", sa.String(length=40), nullable=False),
        sa.Column("commission_model", sa.String(length=40), nullable=False),
        sa.Column("risk_profile", sa.String(length=30), nullable=False),
        sa.Column("starting_balance", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("account_currency", sa.String(length=10), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.Text(), nullable=False),
        sa.Column("ai_models", sa.Text(), nullable=False),
        sa.Column("metrics", sa.Text(), nullable=False),
        sa.Column("validation", sa.Text(), nullable=False),
        sa.Column("survives_all", sa.Boolean(), nullable=True),
        sa.Column("is_evidence", sa.Boolean(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("final_balance", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("net_pnl", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("max_drawdown_pct", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("signals_generated", sa.Integer(), nullable=False),
        sa.Column("proposals_made", sa.Integer(), nullable=False),
        sa.Column("rejections", sa.Integer(), nullable=False),
        sa.Column("started_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("completed_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.CheckConstraint("status IN ('COMPLETED', 'FAILED')", name="ck_backtest_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_backtest_reproducibility", ["manifest_hash", "result_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_is_reproducible"), ["is_reproducible"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_manifest_hash"), ["manifest_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_provenance"), ["provenance"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_result_hash"), ["result_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_strategy_key"), ["strategy_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_backtest_runs_survives_all"), ["survives_all"], unique=False
        )
        batch_op.create_index(
            "ix_backtest_strategy_created", ["strategy_key", "created_at"], unique=False
        )

    op.create_table(
        "backtest_equity_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("equity", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("balance", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("drawdown_pct", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_equity_run_sequence"),
    )
    with op.batch_alter_table("backtest_equity_points", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backtest_equity_points_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "backtest_trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("strategy_key", sa.String(length=80), nullable=False),
        sa.Column("entry_at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("exit_at", nemonis_db.types.UTCDateTime(), nullable=True),
        sa.Column("entry_price", nemonis_db.types.DecimalText(), nullable=False),
        sa.Column("exit_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("stop_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("target_price", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("lots", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("exit_reason", sa.String(length=30), nullable=False),
        sa.Column("pnl", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("r_multiple", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("commission", nemonis_db.types.DecimalText(), nullable=True),
        sa.Column("session", sa.String(length=20), nullable=False),
        sa.Column("regime_label", sa.String(length=30), nullable=False),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="ck_backtest_trade_direction"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_trade_run_sequence"),
    )
    with op.batch_alter_table("backtest_trades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backtest_trades_instrument"), ["instrument"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_backtest_trades_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backtest_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backtest_trades_run_id"))
        batch_op.drop_index(batch_op.f("ix_backtest_trades_instrument"))

    op.drop_table("backtest_trades")
    with op.batch_alter_table("backtest_equity_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backtest_equity_points_run_id"))

    op.drop_table("backtest_equity_points")
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_backtest_strategy_created")
        batch_op.drop_index(batch_op.f("ix_backtest_runs_survives_all"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_strategy_key"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_result_hash"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_provenance"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_manifest_hash"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_is_reproducible"))
        batch_op.drop_index(batch_op.f("ix_backtest_runs_created_at"))
        batch_op.drop_index("ix_backtest_reproducibility")

    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
