"""order lifecycle history on paper orders

Revision ID: b037e7026ce6
Revises: 85ccbcfc5dac
Create Date: 2026-07-30 12:03:22.120674

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are referenced by qualified name in autogenerated schemas.


# revision identifiers, used by Alembic.
revision: str = "b037e7026ce6"
down_revision: str | Sequence[str] | None = "85ccbcfc5dac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paper_working_orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lifecycle_state", sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column("lifecycle_history", sa.Text(), nullable=False))
        batch_op.drop_column("lifecycle")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paper_working_orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lifecycle", sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column("lifecycle_history")
        batch_op.drop_column("lifecycle_state")

    # ### end Alembic commands ###
