"""persist paper risk decisions

Revision ID: d8aa09b79e54
Revises: e904a0705131
Create Date: 2026-07-30 12:45:11.658354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types are referenced by qualified name in autogenerated schemas.
import nemonis_db.types


# revision identifiers, used by Alembic.
revision: str = "d8aa09b79e54"
down_revision: Union[str, Sequence[str], None] = "e904a0705131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=40), nullable=False),
        sa.Column("at", nemonis_db.types.UTCDateTime(), nullable=False),
        sa.Column("strategy_id", sa.String(length=80), nullable=False),
        sa.Column("verdict", sa.String(length=30), nullable=False),
        sa.Column("reason_code", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("paper_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_paper_decision_session_reason", ["session_id", "reason_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_paper_decisions_at"), ["at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_paper_decisions_reason_code"), ["reason_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_paper_decisions_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_paper_decisions_strategy_id"), ["strategy_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_paper_decisions_verdict"), ["verdict"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paper_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_decisions_verdict"))
        batch_op.drop_index(batch_op.f("ix_paper_decisions_strategy_id"))
        batch_op.drop_index(batch_op.f("ix_paper_decisions_session_id"))
        batch_op.drop_index(batch_op.f("ix_paper_decisions_reason_code"))
        batch_op.drop_index(batch_op.f("ix_paper_decisions_at"))
        batch_op.drop_index("ix_paper_decision_session_reason")

    op.drop_table("paper_decisions")
    # ### end Alembic commands ###
