"""trade excursions and broker id

Revision ID: e23152bde812
Revises: 8c0f8ac1ea36
Create Date: 2026-07-29 13:57:11.199312

"""

from collections.abc import Sequence

# Custom column types are referenced by qualified name in autogenerated schemas.
import nemonis_db.types
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e23152bde812"
down_revision: str | Sequence[str] | None = "8c0f8ac1ea36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backtest_trades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trade_id", sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column("mfe_pips", nemonis_db.types.DecimalText(), nullable=True))
        batch_op.add_column(sa.Column("mae_pips", nemonis_db.types.DecimalText(), nullable=True))
        batch_op.add_column(sa.Column("ambiguous_exit", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backtest_trades", schema=None) as batch_op:
        batch_op.drop_column("ambiguous_exit")
        batch_op.drop_column("mae_pips")
        batch_op.drop_column("mfe_pips")
        batch_op.drop_column("trade_id")

    # ### end Alembic commands ###
