"""label paper sessions by bar source

Revision ID: e904a0705131
Revises: b037e7026ce6
Create Date: 2026-07-30 12:19:31.497642

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are referenced by qualified name in autogenerated schemas.


# revision identifiers, used by Alembic.
revision: str = "e904a0705131"
down_revision: str | Sequence[str] | None = "b037e7026ce6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paper_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bar_source", sa.String(length=20), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_paper_sessions_bar_source"), ["bar_source"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("paper_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_sessions_bar_source"))
        batch_op.drop_column("bar_source")

    # ### end Alembic commands ###
