"""initial schema: safety spine

Revision ID: f5af53433bee
Revises:
Create Date: 2026-07-27 15:43:00.127435

"""

from collections.abc import Sequence

import meridian_db.types
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5af53433bee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("starting_balance", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("balance", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("equity", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("high_water_mark", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("prop_profile_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.String(length=40), nullable=True),
        sa.Column("actor", sa.String(length=60), nullable=False),
        sa.Column("request_id", sa.String(length=40), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("prev_hash", sa.String(length=80), nullable=False),
        sa.Column("hash", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.Column("created_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
        sa.UniqueConstraint("sequence", name="uq_audit_sequence"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_events_sequence"), ["sequence"], unique=True)

    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("raised_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.Column("resolved_at", meridian_db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL')", name="ck_incident_severity"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_raised_at"), ["raised_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_incidents_severity"), ["severity"], unique=False)

    op.create_table(
        "instruments",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("broker_symbol", sa.String(length=40), nullable=True),
        sa.Column("base_ccy", sa.String(length=3), nullable=False),
        sa.Column("quote_ccy", sa.String(length=3), nullable=False),
        sa.Column("digits", sa.Integer(), nullable=False),
        sa.Column("pip_size", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("contract_size", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("min_lot", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("lot_step", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("max_lot", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("stop_level_points", sa.Integer(), nullable=False),
        sa.Column("freeze_level_points", sa.Integer(), nullable=False),
        sa.Column("margin_rate", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("commission_per_lot", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("swap_long", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("swap_short", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("spec_source", sa.String(length=200), nullable=True),
        sa.Column("spec_verified_at", meridian_db.types.UTCDateTime(), nullable=True),
        sa.Column("created_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint("lot_step > '0'", name="ck_instrument_lot_step_positive"),
        sa.CheckConstraint("min_lot > '0'", name="ck_instrument_min_lot_positive"),
        sa.CheckConstraint("pip_size > '0'", name="ck_instrument_pip_size_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instruments_symbol"), ["symbol"], unique=True)

    op.create_table(
        "kill_switch_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("engaged", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=60), nullable=False),
        sa.Column("at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kill_switch_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kill_switch_events_at"), ["at"], unique=False)

    op.create_table(
        "trade_proposals",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("account_id", sa.String(length=40), nullable=False),
        sa.Column("instrument_id", sa.String(length=40), nullable=False),
        sa.Column("strategy_version_id", sa.String(length=40), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("entry_price", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("stop_price", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("target_price", meridian_db.types.DecimalText(), nullable=True),
        sa.Column("requested_risk_pct", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("confidence", meridian_db.types.DecimalText(), nullable=True),
        sa.Column("proposal_hash", sa.String(length=80), nullable=False),
        sa.Column("event_time", meridian_db.types.UTCDateTime(), nullable=False),
        sa.Column("decision_time", meridian_db.types.UTCDateTime(), nullable=False),
        sa.Column("created_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="ck_proposal_direction"),
        sa.CheckConstraint("entry_price > '0'", name="ck_proposal_entry_positive"),
        sa.CheckConstraint("stop_price > '0'", name="ck_proposal_stop_positive"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trade_proposals", schema=None) as batch_op:
        batch_op.create_index(
            "ix_proposal_account_time", ["account_id", "event_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_trade_proposals_proposal_hash"), ["proposal_hash"], unique=False
        )

    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("proposal_id", sa.String(length=40), nullable=False),
        sa.Column("proposal_hash", sa.String(length=80), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("requested_size_lots", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("final_size_lots", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("requested_risk_pct", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("final_risk_pct", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("risk_amount_account_ccy", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("binding_constraint", sa.String(length=60), nullable=True),
        sa.Column("reason_codes", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("before_after", sa.Text(), nullable=False),
        sa.Column("rules_evaluated", sa.Integer(), nullable=False),
        sa.Column("rules_passed", sa.Integer(), nullable=False),
        sa.Column("rule_profile_version", sa.String(length=60), nullable=False),
        sa.Column("prop_profile_version", sa.String(length=60), nullable=True),
        sa.Column("evaluated_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.Column("created_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint("final_size_lots >= '0'", name="ck_risk_size_non_negative"),
        sa.CheckConstraint(
            "verdict IN ('APPROVED', 'APPROVED_REDUCED', 'REJECTED')", name="ck_risk_verdict"
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_assessments_proposal_hash"), ["proposal_hash"], unique=False
        )

    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("account_id", sa.String(length=40), nullable=False),
        sa.Column("instrument_id", sa.String(length=40), nullable=False),
        sa.Column("proposal_id", sa.String(length=40), nullable=False),
        sa.Column("risk_decision_id", sa.String(length=40), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("size_lots", meridian_db.types.DecimalText(), nullable=False),
        sa.Column("limit_price", meridian_db.types.DecimalText(), nullable=True),
        sa.Column("stop_loss", meridian_db.types.DecimalText(), nullable=True),
        sa.Column("take_profit", meridian_db.types.DecimalText(), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("created_at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="ck_order_direction"),
        sa.CheckConstraint("size_lots > '0'", name="ck_order_size_positive"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_assessments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orders_risk_decision_id"), ["risk_decision_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_orders_state"), ["state"], unique=False)

    op.create_table(
        "order_state_transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=40), nullable=False),
        sa.Column("from_state", sa.String(length=30), nullable=True),
        sa.Column("to_state", sa.String(length=30), nullable=False),
        sa.Column("actor", sa.String(length=60), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("at", meridian_db.types.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_state_transitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_state_transitions_order_id"), ["order_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_state_transitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_state_transitions_order_id"))

    op.drop_table("order_state_transitions")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_state"))
        batch_op.drop_index(batch_op.f("ix_orders_risk_decision_id"))

    op.drop_table("orders")
    with op.batch_alter_table("risk_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_assessments_proposal_hash"))

    op.drop_table("risk_assessments")
    with op.batch_alter_table("trade_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_proposals_proposal_hash"))
        batch_op.drop_index("ix_proposal_account_time")

    op.drop_table("trade_proposals")
    with op.batch_alter_table("kill_switch_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kill_switch_events_at"))

    op.drop_table("kill_switch_events")
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instruments_symbol"))

    op.drop_table("instruments")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_severity"))
        batch_op.drop_index(batch_op.f("ix_incidents_raised_at"))

    op.drop_table("incidents")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_sequence"))
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_entity_id"))

    op.drop_table("audit_events")
    op.drop_table("accounts")
    # ### end Alembic commands ###
