"""Domain enumerations.

Reason codes are a stable public contract: they are written into immutable audit
records, so renaming one is a data migration, not a refactor (development.md).
"""

from __future__ import annotations

from enum import StrEnum


class Direction(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class OrderState(StrEnum):
    """Execution state machine. Transitions validated in ``state_machine.py``."""

    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    RISK_PENDING = "RISK_PENDING"
    REJECTED = "REJECTED"
    RISK_APPROVED = "RISK_APPROVED"
    HUMAN_APPROVAL_PENDING = "HUMAN_APPROVAL_PENDING"
    APPROVED = "APPROVED"
    SUBMITTED_TO_PAPER_BROKER = "SUBMITTED_TO_PAPER_BROKER"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    MANAGED = "MANAGED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class RiskVerdict(StrEnum):
    APPROVED = "APPROVED"
    APPROVED_REDUCED = "APPROVED_REDUCED"
    REJECTED = "REJECTED"


class AICritiqueDecision(StrEnum):
    SUPPORT = "SUPPORT"
    OPPOSE = "OPPOSE"
    ABSTAIN = "ABSTAIN"
    NEED_MORE_DATA = "NEED_MORE_DATA"


class DataQualityVerdict(StrEnum):
    OK = "OK"
    DEGRADED = "DEGRADED"
    INVALID = "INVALID"


class Session(StrEnum):
    SYDNEY = "SYDNEY"
    TOKYO = "TOKYO"
    LONDON = "LONDON"
    NEW_YORK = "NEW_YORK"
    CLOSED = "CLOSED"


class Timeframe(StrEnum):
    M1 = "M1"
    M5 = "M5"
    M15 = "M15"
    M30 = "M30"
    H1 = "H1"
    H4 = "H4"
    D1 = "D1"
    W1 = "W1"

    @property
    def minutes(self) -> int:
        return {
            "M1": 1,
            "M5": 5,
            "M15": 15,
            "M30": 30,
            "H1": 60,
            "H4": 240,
            "D1": 1440,
            "W1": 10080,
        }[self.value]


class PromotionStatus(StrEnum):
    """Strategy lifecycle. Advances only through the pipeline; never skipped."""

    DRAFT = "DRAFT"
    BACKTESTED = "BACKTESTED"
    VALIDATED = "VALIDATED"
    OUT_OF_SAMPLE_TESTED = "OUT_OF_SAMPLE_TESTED"
    PAPER_DEPLOYED = "PAPER_DEPLOYED"
    PROMOTED = "PROMOTED"
    RETIRED = "RETIRED"


class ResultProvenance(StrEnum):
    """Where a performance number came from (backtesting-methodology.md §1).

    Attached to every metric so a number can never be displayed without it.
    """

    IN_SAMPLE = "IN_SAMPLE"
    VALIDATION = "VALIDATION"
    OUT_OF_SAMPLE = "OUT_OF_SAMPLE"
    WALK_FORWARD = "WALK_FORWARD"
    PAPER = "PAPER"
    SYNTHETIC = "SYNTHETIC"


class RejectionCode(StrEnum):
    """Risk-engine reason codes (risk-engine.md §4).

    Stable contract — these strings live in immutable audit records.
    """

    # Tier A — blocking gates
    KILL_SWITCH_ENGAGED = "KILL_SWITCH_ENGAGED"
    MODE_FORBIDS_EXECUTION = "MODE_FORBIDS_EXECUTION"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    MARKET_DATA_INVALID = "MARKET_DATA_INVALID"
    MARKET_CLOSED = "MARKET_CLOSED"
    WEEKEND_BLOCK = "WEEKEND_BLOCK"
    ROLLOVER_BLOCK = "ROLLOVER_BLOCK"
    NEWS_WINDOW_BLOCK = "NEWS_WINDOW_BLOCK"
    ABNORMAL_SPREAD = "ABNORMAL_SPREAD"
    ABNORMAL_VOLATILITY = "ABNORMAL_VOLATILITY"
    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    ACCOUNT_STATE_AMBIGUOUS = "ACCOUNT_STATE_AMBIGUOUS"
    EMERGENCY_SHUTDOWN = "EMERGENCY_SHUTDOWN"

    # Tier B — account and prop-firm
    DAILY_LOSS_LIMIT_REACHED = "DAILY_LOSS_LIMIT_REACHED"
    DAILY_LOSS_WOULD_BREACH = "DAILY_LOSS_WOULD_BREACH"
    TOTAL_LOSS_LIMIT_REACHED = "TOTAL_LOSS_LIMIT_REACHED"
    TOTAL_LOSS_WOULD_BREACH = "TOTAL_LOSS_WOULD_BREACH"
    TRAILING_DRAWDOWN_BREACH = "TRAILING_DRAWDOWN_BREACH"
    PROP_RULE_VIOLATION = "PROP_RULE_VIOLATION"
    PROP_RULE_BUFFER = "PROP_RULE_BUFFER"

    # Tier C — exposure
    MAX_OPEN_RISK = "MAX_OPEN_RISK"
    MAX_INSTRUMENT_EXPOSURE = "MAX_INSTRUMENT_EXPOSURE"
    MAX_CURRENCY_EXPOSURE = "MAX_CURRENCY_EXPOSURE"
    MAX_CORRELATED_EXPOSURE = "MAX_CORRELATED_EXPOSURE"
    MAX_SIMULTANEOUS_POSITIONS = "MAX_SIMULTANEOUS_POSITIONS"
    MAX_TRADES_PER_SESSION = "MAX_TRADES_PER_SESSION"
    MAX_MARGIN_UTILISATION = "MAX_MARGIN_UTILISATION"
    # Portfolio-level, added with ADR-0007's multi-strategy model.
    MAX_STRATEGY_BUDGET = "MAX_STRATEGY_BUDGET"
    PORTFOLIO_BUDGET_EXHAUSTED = "PORTFOLIO_BUDGET_EXHAUSTED"

    # Tier D — quality
    BELOW_MIN_REWARD_RISK = "BELOW_MIN_REWARD_RISK"
    BELOW_MIN_CONFIDENCE = "BELOW_MIN_CONFIDENCE"
    STOP_DISTANCE_INVALID = "STOP_DISTANCE_INVALID"
    STOP_TOO_TIGHT = "STOP_TOO_TIGHT"
    STOP_TOO_WIDE = "STOP_TOO_WIDE"
    STOP_INSIDE_BROKER_STOP_LEVEL = "STOP_INSIDE_BROKER_STOP_LEVEL"
    EXCESSIVE_SLIPPAGE_ESTIMATE = "EXCESSIVE_SLIPPAGE_ESTIMATE"
    CONSECUTIVE_LOSS_COOLDOWN = "CONSECUTIVE_LOSS_COOLDOWN"
    DAILY_LOSS_COOLDOWN = "DAILY_LOSS_COOLDOWN"
    WEEKLY_LOSS_COOLDOWN = "WEEKLY_LOSS_COOLDOWN"
    STRATEGY_NOT_APPROVED = "STRATEGY_NOT_APPROVED"
    INSTRUMENT_NOT_APPROVED = "INSTRUMENT_NOT_APPROVED"
    SESSION_NOT_APPROVED = "SESSION_NOT_APPROVED"

    # Tier E — throttle
    DRAWDOWN_THROTTLE = "DRAWDOWN_THROTTLE"

    # Sizing and integrity
    SIZE_BELOW_MINIMUM_LOT = "SIZE_BELOW_MINIMUM_LOT"
    SIZING_INVARIANT_VIOLATED = "SIZING_INVARIANT_VIOLATED"
    FX_CONVERSION_UNAVAILABLE = "FX_CONVERSION_UNAVAILABLE"
    PROPOSAL_HASH_MISMATCH = "PROPOSAL_HASH_MISMATCH"


class AuditEventType(StrEnum):
    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    RISK_EVALUATED = "RISK_EVALUATED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_STATE_CHANGED = "ORDER_STATE_CHANGED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_CLOSED = "POSITION_CLOSED"
    RISK_SETTING_CHANGED = "RISK_SETTING_CHANGED"
    RISK_PROFILE_CHANGED = "RISK_PROFILE_CHANGED"
    PROP_PROFILE_CHANGED = "PROP_PROFILE_CHANGED"
    MODE_CHANGED = "MODE_CHANGED"
    KILL_SWITCH_ENGAGED = "KILL_SWITCH_ENGAGED"
    KILL_SWITCH_RELEASED = "KILL_SWITCH_RELEASED"
    MODEL_INVOKED = "MODEL_INVOKED"
    VAULT_SYNCED = "VAULT_SYNCED"
    INCIDENT_RAISED = "INCIDENT_RAISED"
    BACKTEST_STARTED = "BACKTEST_STARTED"
    BACKTEST_COMPLETED = "BACKTEST_COMPLETED"
    STRATEGY_PROMOTED = "STRATEGY_PROMOTED"
    SYSTEM_STARTED = "SYSTEM_STARTED"
